name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version

    - name: Install dependencies for client
      run: |
        cd client
        npm install

    - name: Run tests for client
      run: |
        cd client
        npm test

    - name: Check for vulnerabilities in client
      run: |
        cd client
        npm audit --audit-level=high
        if [ $? -ne 0 ]; then
          echo "Vulnerabilities found, failing the build."
          exit 1
        fi

  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version

    - name: Install dependencies for server
      run: |
        cd server
        npm install

    - name: Run tests for server
      run: |
        cd server
        npm test

    - name: Check for vulnerabilities in server
      run: |
        cd server
        npm audit --audit-level=high
        if [ $? -ne 0 ]; then
          echo "Vulnerabilities found, failing the build."
          exit 1
        fi
